In [1]:
import pandas as pd
import plotly.express as px

In [3]:
df= pd.read_csv("sheet.csv")

In [4]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities
0,Haircare,SKU51,26.700761,61,154,9866.465458,Male,100,4,52
1,Cosmetics,SKU38,52.075931,75,705,9692.318040,Non-binary,69,1,88
2,Skincare,SKU31,50.847393,28,168,9655.135103,Male,6,17,44
3,Skincare,SKU90,13.881913,56,320,9592.633570,Non-binary,66,18,96
4,Haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    str
 1   SKU                      100 non-null    str
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    str
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
dtypes: float64(2), int64(5), str(3)
memory usage: 9.9 KB

In [6]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,49.464177,48.400000,460.990000,5776.048202,47.770000,15.960000,49.220000
std,31.168996,30.743317,303.780074,2732.841719,31.369372,8.785801,26.784429
min,1.699976,1.000000,8.000000,1061.620000,0.000000,1.000000,1.000000
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000
50%,51.239830,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000
75%,77.198228,75.000000,704.250000,8253.976920,73.000000,24.000000,71.250000
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000

In [7]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [10]:
revenue=df.groupby("Product type")["Revenue generated"].sum().reset_index()
px.bar(revenue,x="Product type",y="Revenue generated",title="Revenue by Product Type")

In [11]:
px.histogram(df,x="Stock levels",title="Stock Level Distribution")

In [12]:
px.histogram(df,x="Lead times",title="Lead times Distribution")

In [13]:
px.pie(df,names="Customer demographics",title="Customer demographics")

In [15]:
px.scatter(df,x="Price",y="Revenue generated",color="Product type",title="Price vs Revenue")

In [16]:
df.corr(numeric_only=True)

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities
Price,1.000000,0.019049,0.005744,0.038327,0.078352,0.044854,0.095768
Availability,0.019049,1.000000,0.087496,-0.075170,-0.025900,0.170439,0.143769
Number of products sold,0.005744,0.087496,1.000000,-0.001641,0.022189,-0.046419,0.015992
Revenue generated,0.038327,-0.075170,-0.001641,1.000000,-0.158480,-0.057296,0.029422
Stock levels,0.078352,-0.025900,0.022189,-0.158480,1.000000,0.072571,-0.111455
Lead times,0.044854,0.170439,-0.046419,-0.057296,0.072571,1.000000,0.105459
Order quantities,0.095768,0.143769,0.015992,0.029422,-0.111455,0.105459,1.000000